## Introdução ao Ajustamento de Observações - Aplicações Geodésicas
## 2ª ed. Camil Gemael, Alvaro Muriel Lima Machado e Romualdo Wandresen
### Exercício 3.12.8  

As direções $d_{i}$ foram observadas com o mesmo desvio padrão $\sigma = 3"$ e sem correlação.<br><br>
<img src="diagramaDirecoes.png" align="left" style="width:200px"> <br><br><br><br><br><br><br><br><br><br>

Calcular o coeficiente de correlação entre os ângulos $(b_{1}$ e $b_{2})$, $(b_{1}$ e $b_{3})$ e $(b_{1}$ e $b_{4})$.

O modelo matemático que liga as direções aos ângulos é linear:

$b_{1} = -d_{1}+d_{2}$<br>
$b_{2} = -d_{1}+d_{3}$<br>
$b_{3} = -d_{1}+d_{4}$<br>
$b_{4} = -d_{3}+d_{4}$<br>

Matriz Variância-Covariância

$\Sigma_{b} = G\Sigma_{d}G^{T}$, onde $G$ é a matrix Jacobiana e $\Sigma_{d}$ é a matrix covariância.

In [48]:
# Importa a biblioteca numpy para trabalhar com arrays e matrizes
import numpy as np
from math import sqrt

# Matriz das derivadas das equações
G = np.matrix([[-1, 1, 0, 0], [-1, 0, 1, 0], [-1, 0, 0, 1], [0, 0, -1, 1]])
print(G)

[[-1  1  0  0]
 [-1  0  1  0]
 [-1  0  0  1]
 [ 0  0 -1  1]]


In [40]:
# Gera a matriz diagonal com as variâncias das observações [segundos²]
arr = np.array([3,3,3,3])
Sigma_d = np.diag(arr)
print(Sigma_d)

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]


In [44]:
# Calcula a MVC (segundos²)
Sigma_b = G*Sigma_d*G.T
print(Sigma_b)

[[ 6  3  3  0]
 [ 3  6  3 -3]
 [ 3  3  6  3]
 [ 0 -3  3  6]]


Os coeficientes de correlação podem ser obtidos pela equação abaixo:

$\rho_{ij} = \frac{\sigma_{ij}}{\sigma_{i}\sigma_{j}}$

$\rho_{12} = \frac{\sigma_{12}}{\sigma_{1}\sigma_{2}}$, $\rho_{13} = \frac{\sigma_{13}}{\sigma_{1}\sigma_{3}}$, $\rho_{14} = \frac{\sigma_{14}}{\sigma_{1}\sigma_{4}}$

In [65]:
# Coeficiente de correlação para (b1 e b2)
b12 = Sigma_b[0,1]/sqrt(Sigma_b[0,0]*Sigma_b[1,1])

# Coeficiente de correlação para (b1 e b3)
b13 = Sigma_b[0,2]/sqrt(Sigma_b[0,0]*Sigma_b[2,2])

#Coeficiente de correlação para (b1 e b4)
b14 = Sigma_b[0,3]/sqrt(Sigma_b[0,0]*Sigma_b[3,3])

print("Correlação(b1,b2) = %5.3f" %b12)
print("Correlação(b1,b3) = %5.3f" %b13)
print("Correlação(b1,b4) = %5.3f" %b14)

Correlação(b1,b2) = 0.500
Correlação(b1,b3) = 0.500
Correlação(b1,b4) = 0.000
